theme: just-the-docs
title: Open Voice Network - Doc Site
description: OVON published and WIP artifacts, docs, etc.
logo: "/images/ovon-logo.jpg"
timezone: America/New_York
color_scheme: light
search_enabled: true
show_downloads: true
aux_links:
  "OVON Docs on GitHub":
    - "//github.com/open-voice-network/docs"
heading_anchors: true
footer_content: "Copyright &copy; Open Voice Network 2017-2022"
markdown: kramdown
destination: docs
